server:
  port: 8089
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8070/realms/master/protocol/openid-connect/certs"
