services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: learning-keycloak
    ports:
      - "8070:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
